name: boards
description: "A new Flutter project."
publish_to: 'none'
version: 0.5.03+35

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  parse_server_sdk_flutter: ^8.0.0
  google_fonts: ^4.0.4
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_cropper: ^4.0.1
  http: ^0.13.6
  shared_preferences: ^2.3.0
  path: ^1.9.0
  cached_network_image: ^3.3.1
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  get_it: ^8.0.1
  flutter_carousel_slider: ^1.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  xml: ^6.5.0
  equatable: ^2.0.5
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.4
  image: ^4.2.0
  flutter_dotenv: ^5.1.0
  material_symbols_icons: ^4.2789.0
  webview_flutter: ^4.10.0
  csv: ^6.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  cloud_functions: ^5.1.5
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  # file_picker: ^8.1.5
  file_picker:
    path: ../../Packages/flutter_file_picker
  flutter_stripe: ^11.3.0

dev_dependencies:
  intl_utils: ^2.8.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
